apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.name | default .Release.Name }}-pgbackrest
          restartPolicy: OnFailure
          containers:
          - name: pgo-backup
            image: registry.developers.crunchydata.com/crunchydata/pgo-client:ubi8-5.5.1
            env:
            - name: PGO_NAMESPACE
              value: "{{ .Release.Namespace }}"
            command:
              - "/bin/bash"
              - "-c"
              - |
                pgo backup {{ .Values.name | default .Release.Name }} --namespace={{ .Release.Namespace }}
